name: 'Write File'
description: 'Write contents to a file and delete afterwards'
inputs:
  contents:
    description: 'The contents of the file'
    required: true
  path:
    description: 'Output file path'
    required: true

runs:
  using: 'node16'
  main: 'index.js'
  post: 'cleanup.js'
